version: '3'

services:
  tool-nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - tool-application
    environment:
      - TZ="Asia/Seoul"
    ports:
      - "80:80"
  tool-redis:
    image: redis:latest
    container_name: tool_redis
    hostname: tool
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  tool-database:
    image: mysql:8.0
    container_name: tool_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  tool-application:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    container_name: tool_application
    restart: always
    expose:
      - 8080
    depends_on:
      - tool-database
      - tool-redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul