version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - tool-application
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  tool-redis:
    image: redis:latest
    container_name: tool_redis
    hostname: tool
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379

  tool-database:
    image: mysql:8.0
    container_name: tool_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  tool-application:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    container_name: tool_application
    restart: always
    expose:
      - 8080
    depends_on:
      - tool-database
      - tool-redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/jeon050419/images:/app/files
  certbot:
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"