logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            BasicBinder: TRACE
    web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 28x82rhq
    url: jdbc:mysql://localhost:3306/Tool?autoReconnect=true
    username: root
  jpa:
    database: sql-server
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
