logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            BasicBinder: TRACE
    web: DEBUG
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tool1234
    url: jdbc:mysql://34.64.112.157:3306/tool
    username: tool
  redis:
    host: 34.64.112.157
    port: 6379
  jpa:
    database: sql-server
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

jwt:
  refresh-time: 1209600000 # 2주
  access-time: 3600000 # 1시간
  prefix: Bearer
  header: Authorization
  secret-key: dlxogusrhkwjstngidrhkdlehdgnsdmltool
bsm:
  client_id: 98fd44ad
  secret_key: 0cf51f4d6b11d4f7e87ce830ab766a38
image:
  path: /app/files/
chatgpt:
  api-key: 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

