logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            BasicBinder: TRACE
    web: DEBUG
spring:
  config:
    import: classpath:/env.yml
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${tool.mysql.password}
    url: ${tool.mysql.url}
    username: ${tool.mysql.username}
  redis:
    host: ${tool.redis.host}
    port: ${tool.redis.port}
  jpa:
    database: sql-server
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

jwt:
  refresh-time: 1209600000 # 2주
  access-time: 3600000 # 1시간
  prefix: Bearer
  header: Authorization
  secret-key: ${tool.jwt.secret-key}
bsm:
  client_id: ${tool.bsm.client_id}
  secret_key: ${tool.bsm.secret_key}
image:
  path: ${tool.image.path}
chatgpt:
  api-key: ${tool.chatgpt.api-key}

