name: Java CD with Gradle

on:
  push:
    branches: [ master ]

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      ## jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # https://github.com/actions/setup-java

      ## gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      ## text application build
      - name: Test with Gradle
        run: ./gradlew test

      ## docker build & push
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p %{{secrets.DOCKER_PASSWORD }}

      
